### ISSUE TITLE
Changing the  SecurityConfiguration extends KeycloakWebSecurityConfigurerAdapter  class gets vaadin connection fails 

### ISSUE THREAD

**Issue by ramanamuttana** [simasch/vaadin-keycloak#1]
@simasch I have  changed the  **_public class SecurityConfiguration extends VaadinWebSecurity_**  to **public class SecurityConfiguration extends  KeycloakWebSecurityConfigurerAdapter_** , added some methods for registration of a provider , then i am getting connection fail error,, not able to render the UI . 
Reason: the main reason for adding the   KeycloakWebSecurityConfigurerAdapter is , i want to get the access_token , once the user logged in , that is on the client side not on the service side , is there a way to do on the client side to get Access_token

**Comment by simasch** [comment]
KeycloakWebSecurityConfigurerAdapter cannot be used with Spring Boot 3:
https://stackoverflow.com/questions/74571191/use-keycloak-spring-adapter-with-spring-boot-3

Why did you change that?

**Comment by ramanamuttana** [comment]
@simasch   i am not using spring boot 3 , i am using spring boot 2.7.8 ,( from spring boot 3 they removed  the extension ) 
no errors but UI is not rendered 
![Screenshot 2023-06-30 151651](https://github.com/simasch/vaadin-keycloak/assets/18735962/8fc398d0-59c9-4cd5-827c-9041ff6c61ab)

**Comment by simasch** [comment]
If you want to use security with Vaadin you must use the adapter from Vaadin.

Which Vaadin version do you use? 24 requires Spring Boot 3

**Comment by ramanamuttana** [comment]
i am using vaadin 23.2.8 , i want to use the security from keycloak adapter and spring boot ,  and use only vaadin  for UI , does it possible ? i am using the **_keycloak-spring-boot-starter_**    
2) now if i want to get the **_access_token_** from keycloak , is there a way for that ?

**Comment by simasch** [comment]
You don't need the keycloak starter. Use this:

```
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-security</artifactId>
    </dependency>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-oauth2-client</artifactId>
    </dependency>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-oauth2-resource-server</artifactId>
    </dependency>
```

And the configuration will be something like this:

```
@EnableWebSecurity
@Configuration
public class SecurityConfiguration extends VaadinWebSecurity {

  private final KeycloakLogoutHandler keycloakLogoutHandler;

  public SecurityConfiguration(KeycloakLogoutHandler keycloakLogoutHandler) {
    this.keycloakLogoutHandler = keycloakLogoutHandler;
  }

  @Bean
  protected SessionAuthenticationStrategy sessionAuthenticationStrategy() {
    return new RegisterSessionAuthenticationStrategy(new SessionRegistryImpl());
  }

  @Override
  protected void configure(HttpSecurity http) throws Exception {
    http.csrf(AbstractHttpConfigurer::disable);

    http.cors(c -> new CorsConfigurer<>());

    http.authorizeHttpRequests(c ->
      c.requestMatchers(
        new AntPathRequestMatcher("/images/*.*"),
        new AntPathRequestMatcher("/line-awesome/**/*.svg")
      ).permitAll()
    );

    http.oauth2ResourceServer(c -> c.jwt(Customizer.withDefaults()));

    http.oauth2Login(Customizer.withDefaults());

    http.logout(c -> c.addLogoutHandler(keycloakLogoutHandler).logoutSuccessUrl("/"));

    super.configure(http);
  }

}

```

The code is for Spring Boot 3 so you have to adapt it.

**Comment by ramanamuttana** [comment]
@simasch  , My main concern is about access_tokens ,can i get the access_token now with this new changes in the code?

**Comment by simasch** [comment]
Sure this code is from a project running in production

**Comment by ramanamuttana** [comment]
@simasch thanks , i will try with code

**Comment by ramanamuttana** [comment]
@simasch with the above code ,it worked thanks

**Comment by simasch** [comment]
[like]  Simon Martinelli, 72 Services LLC reacted to your message:
________________________________
